### ISSUE TITLE
-t not working

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#119]
~/Music $ sof djcarnageofficial -t carnage-mase-in-97-ft-lil-yachty
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 100, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 181, in process_soundcloud
    track_data = get_soundcloud_data(artist_url)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 434, in get_soundcloud_data
    request = requests.get(url)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 447, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 378, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 303, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 360, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL u'djcarnageofficial': No schema supplied. Perhaps you meant http://djcarnageofficial?

**Comment by Miserlou** [comment]
Nevermind.
