### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#120]
~/Music $ sof https://soundcloud.com/djcarnageofficial/carnage-mase-in-97-ft-lil-yachty
Scraping: Carnage - Mase In &#39;97 Ft. Lil Yachty (Prod. By Carnage &amp; Charlie Heat)
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 100, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 197, in process_soundcloud
    filename = download_file(hard_track_url, filename)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 972, in download_file
    if url[0:2] == '//':
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Miserlou** [comment]
Nevermind.
