### ISSUE TITLE
Immediate crash while downloading from bandicamp.

### ISSUE THREAD

**Issue by Wojtas121PL** [Miserlou/SoundScrape#127]
When i try to scrape this bandicamp, it just crashes with diffrent errors on diffrent occasions. I tried adding different atributes, deleting the forder it SOMETIMES makes but none of that seems to improve it. Please tell me that i'm doing something wrong, as i really need this scrape 😞 

Bandicamp i'm trying to scrape:
https://determination-ut.bandcamp.com/album/determination-the-purple-side

Error after first try:
soundscrape -b https://determination-ut.bandcamp.com/album/determination-the-purple-side
Active code page: 65001
Downloading: When the World was Full of Wonders
Problem downloading When the World was Full of Wonders
[Errno 2] No such file or directory: u'RichaadEB // Ace Waters - When the World was Full of Wonders.mp3.tmp'
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 100, in main
    process_bandcamp(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 532, in process_bandcamp
    filenames = scrape_bandcamp_url(bc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'], custom_path=vargs['path'])
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 632, in scrape_bandcamp_url
    puts_safe(colored.red("Problem downloading ") + colored.white(track_name))
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 1130, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
  File "c:\python27\lib\encodings\cp852.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 51: ordinal not in range(128)

Another atempt:
soundscrape -b -f https://determination-ut.bandcamp.com/album/determination-the-purple-side
Active code page: 65001
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 100, in main
    process_bandcamp(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 532, in process_bandcamp
    filenames = scrape_bandcamp_url(bc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'], custom_path=vargs['path'])
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 632, in scrape_bandcamp_url
    puts_safe(colored.red("Problem downloading ") + colored.white(track_name))
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 1130, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
LookupError: unknown encoding: cp65001

**Comment by brachna** [comment]
The reason is because it does sanitize with -f, but not without. I found new error as well, while fixing this one.

**Comment by Miserlou** [comment]
Pushed fix
