### ISSUE TITLE
Str has no attribute object error 

### ISSUE THREAD

**Issue by XavierSchiller** [Miserlou/SoundScrape#129]
Any command i use with soundscrape gives me this result, regardless of what kind of command i use with soundcloud. 

Active code page: 65001
Traceback (most recent call last):
  File "c:\users\[user name]\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\[user name]\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\[user name]\AppData\Local\Programs\Python\Python35-32\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\users\[user name]\appdata\local\programs\python\python35-32\lib\site-packages\soundscrape\soundscrape.py", line 90, in main
    vargs['artist_url'] = vargs['artist_url'][0].decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

I am unsure of what I do here.

**Comment by Miserlou** [comment]
Pushed fix
