### ISSUE TITLE
Error when I try to download a soundcloud track.

### ISSUE THREAD

**Issue by fluffyluke707** [Miserlou/SoundScrape#131]
Whenever I try to do the command sounscrape then track url, I am getting this error. I am on Windows 10 and have Python 2.7.12 installed, any way to fix it?
`
> Active code page: 65001
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 113, in main
    process_soundcloud(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 283, in process_soundcloud
    id3_extras=id3_extras)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 452, in download_tracks
    puts_safe(colored.red("Problem downloading ") + colored.white(track['title']))
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 1135, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
LookupError: unknown encoding: cp65001

**Comment by Miserlou** [comment]
Fixed
