### ISSUE TITLE
Fails on Private Tracks (or maybe scrapes)?

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#135]
https://soundcloud.com/zedsdead/too-young-ft-rivers-cuomo-pusha-t/s-5x7ag

Scraping: Too Young (ft. Rivers Cuomo, Pusha T)
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 113, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 212, in process_soundcloud
    filename = download_file(hard_track_url, filename)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 1017, in download_file
    if url[0:2] == '//':
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Evolution0** [comment]
After looking at your code it seems item_id possibly isn't returning the information get_hard_track_url needs anymore? I see you are using the API and already have an idea that it might be causing issues. (Comments in the code right near where I suspect the problems is)

I might poke around the code at some point, it would be a welcome break from bandcamp-dl as there won't be much more for me to do with it soon and I was just about to make my own util for soundcloud that doesn't use the API. (Id much rather support one that already exists)
