### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by tjetzinger** [Miserlou/SoundScrape#148]
>> soundscrape https://soundcloud.com/deep-chills/takeitslow 
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.9/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 113, in main
    process_soundcloud(vargs)
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 192, in process_soundcloud
    hard_track_url = get_hard_track_url(item_id)
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 509, in get_hard_track_url
    json_response = response.json()
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Miserlou** [comment]
Yeah, it's fucked. Damn. 

https://soundcloud.com/vincent_official/alpha

**Comment by Miserlou** [comment]
Fixed
