### ISSUE TITLE
get_soundcloud_api_playlist_data: parsed = response.json(): JSONDecodeError

### ISSUE THREAD

**Issue by Lanchon** [Miserlou/SoundScrape#156]
hey, thanks so much for SoundScrape!

```
$ sudo pip install soundscrape --upgrade

Requirement already up-to-date: soundscrape in /usr/local/lib/python2.7/dist-packages
Cleaning up...

$ soundscrape -f https://soundcloud.com/themagician/sets/magic-tapes

Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 250, in process_soundcloud
    tracks = get_soundcloud_api_playlist_data(resolved.id)['tracks']
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 506, in get_soundcloud_api_playlist_data
    parsed = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

btw, it works fine for other URLs such as:
`https://soundcloud.com/anjunadeep/sets/the-anjunadeep-edition`

**Comment by Miserlou** [comment]
Confirmed

**Comment by SimplicityGuy** [comment]
Duping to #169 which has more information.
