### ISSUE TITLE
KeyError: 'track'

### ISSUE THREAD

**Issue by stevenschmatz** [Miserlou/SoundScrape#160]
I get the following stack trace whenever I run the command `soundscrape muramasamusic`:

```
Scraping: APZIP.01 (free ziptape and beats 1 radio show)
[################################] 4942/4942 - 00:00:01
Traceback (most recent call last):
  File "//anaconda/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.5/site-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "//anaconda/lib/python3.5/site-packages/soundscrape/soundscrape.py", line 285, in process_soundcloud
    d_track = track['track']
KeyError: 'track'
```

Maybe it's an issue with SoundCloud Go only tracks?

**Comment by Miserlou** [comment]
Confirming.
