### ISSUE TITLE
Download all Likes

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#18]
Doesn't work for downloading all of a user's "Likes"

$ soundscrape https://soundcloud.com/troyboi/likes
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.10.2', 'console_scripts', 'soundscrape')()
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 52, in main
    if resolved.kind == 'artist':
AttributeError: 'ResourceList' object has no attribute 'kind'

**Comment by Miserlou** [comment]
Fixed in 0.12.0
