### ISSUE TITLE
mixcloud stopped working?

### ISSUE THREAD

**Issue by technicaltitch** [Miserlou/SoundScrape#192]
I try the following:

```
soundscrape https://www.mixcloud.com/artist/show_from_this_week/
```

I see the following error:

```
Downloading: Gets the show title correctly (.m4a)
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 111, in main
    process_mixcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 718, in process_mixcloud
    filenames = scrape_mixcloud_url(mc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'], custom_path=vargs['path'])
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 759, in scrape_mixcloud_url
    download_file(data['mp3_url'], track_filename)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 1188, in download_file
    r = requests.get(url, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stream22.mixcloud.com', port=443): Max retries exceeded with url: /c/m4a/64/a/0/9/8/0xy9-w1yu-4338-b310-4cdfa85b7013.m4a (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9de640c310>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
```

I'm running soundscrape on Ubuntu 16 Python 2.7.6. mixcloud has worked fine until this week, soundcloud still working fine.

**Comment by jonasbits** [comment]
same error for me - running dietpi ( rasbian ), scraping soundcloud works fine

**Comment by SimplicityGuy** [comment]
MixCloud support was entirely experimental. Prior to starting on PR #241, it was entirely broken, so support for MixCloud was pulled. Adding support back for MixCloud is a large undertaking.
