### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'replace'

### ISSUE THREAD

**Issue by moonym** [Miserlou/SoundScrape#204]
Getting the stack trace from below when using
`soundscrape <artist> -f`
This seems to be occurring for soundcloud only, right now.  Bandcamp works fine for me.

```
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/usr/local/lib/python2.7/dist-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/usr/local/lib/python2.7/dist-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'HTTPError' object has no attribute 'replace'
```

**Comment by RodolfoSalido** [comment]
I recently updated soundscape. I had been using it and downloaded 600+ songs but it no longer works properly and returns a similar error description.

**Comment by cos-of-me** [comment]
Same issue, I can guess the root of the problem may be in:

- soundcloud site
- some library which soundscrape uses

Because it was working just fine and I didn't update soundscrape itself.

**Comment by Zekei** [comment]
This is an exception thrown while handling an original exception that occurs due to a 429 HTTP response:

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/soundscrape/soundscrape.py", line 437, in download_tracks
>     stream = client.get(track['stream_url'], allow_redirects=False, limit=200)
>   File "/usr/lib/python3.6/site-packages/soundcloud/client.py", line 133, in _request
>     return wrapped_resource(make_request(method, url, kwargs))
>   File "/usr/lib/python3.6/site-packages/soundcloud/request.py", line 148, in make_request
>     result.raise_for_status()
>   File "/usr/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 429 Client Error: Unknown for url: https://api.soundcloud.com/tracks/<num>/stream?limit=200&client_id=<client_id>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/soundscrape", line 11, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/soundscrape/soundscrape.py", line 119, in main
>     process_soundcloud(vargs)
>   File "/usr/lib/python3.6/site-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
>     id3_extras=id3_extras)
>   File "/usr/lib/python3.6/site-packages/soundscrape/soundscrape.py", line 460, in download_tracks
>     puts_safe(e)
>   File "/usr/lib/python3.6/site-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
>     puts(text)
>   File "/usr/lib/python3.6/site-packages/clint/textui/core.py", line 57, in puts
>     s = tsplit(s, NEWLINES)
>   File "/usr/lib/python3.6/site-packages/clint/utils.py", line 69, in tsplit
>     string = string.replace(i, final_delimiter)
> AttributeError: 'HTTPError' object has no attribute 'replace'

**Comment by the-nick-dev** [comment]
same problem

**Comment by Vladikamira** [comment]
I also have the same problem

**Comment by GillesJ** [comment]
Same issue.

**Comment by vinz243** [comment]
same

**Comment by remphase** [comment]
same here - is this in progress?

**Comment by boardfish** [comment]
Getting this issue myself when scraping my likes.

**Comment by Lanchon** [comment]
duplicate of #203, please close

**Comment by moonym** [comment]
Sure thing - closing this issue.

**Comment by br101** [comment]
i see this too, but i think it's not related to 429 as in (#203)...

`Downloading: Ajeet Kaur - Ra Ma Da Sa
Problem downloading XXXAjeet Kaur - Ra Ma Da Sa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 437, in download_tracks
    stream = client.get(track['stream_url'], allow_redirects=False, limit=200)
  File "/usr/local/lib/python3.6/dist-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.6/dist-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.soundcloud.com/tracks/452383728/stream?limit=200&client_id=175c043157ffae2c6d5fed16c3d95a4c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/usr/local/lib/python3.6/dist-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/usr/local/lib/python3.6/dist-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'HTTPError' object has no attribute 'replace'`

**Comment by malleable808** [comment]
Same issue as @br101 !

**Comment by douglasrolim** [comment]
Same here
