### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'encode'

### ISSUE THREAD

**Issue by SourceNull** [Miserlou/SoundScrape#206]
`Active code page: 65001
Downloading: 【NEW Release】 Future Cαke  【Album Xfade Demo】
Problem downloading 【NEW Release】 Future Cαke  【Album Xfade Demo】
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\soundscrape\soundscrape.py", line 437, in download_tracks
    stream = client.get(track['stream_url'], allow_redirects=False, limit=200)
  File "c:\program files (x86)\python36-32\lib\site-packages\soundcloud\client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "c:\program files (x86)\python36-32\lib\site-packages\soundcloud\request.py", line 148, in make_request
    result.raise_for_status()
  File "c:\program files (x86)\python36-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Unknown for url: https://api.soundcloud.com/tracks/346978291/stream?limit=200&client_id=175c043157ffae2c6d5fed16c3d95a4c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\soundscrape-script.py", line 11, in <module>
    load_entry_point('soundscrape==0.30.1', 'console_scripts', 'soundscrape')()
  File "c:\program files (x86)\python36-32\lib\site-packages\soundscrape\soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\soundscrape\soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "c:\program files (x86)\python36-32\lib\site-packages\soundscrape\soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "c:\program files (x86)\python36-32\lib\site-packages\soundscrape\soundscrape.py", line 1313, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
AttributeError: 'HTTPError' object has no attribute 'encode'`

**Comment by jaydenrre** [comment]
same problem

**Comment by the-nick-dev** [comment]
same problem

**Comment by the-nick-dev** [comment]
soundscrape -f alexomfg
soundscrape -f spinninrecords
soundscrape -f liquicityrecords
soundscrape -f marshmellomusic
soundscrape -f pegboardnerds
soundscrape -f teminite
soundscrape -f alanwalker
soundscrape -f pixl-music
soundscrape -f haywyre
soundscrape -f nitrofun
soundscrape -f kuuromusic
soundscrape -f slipsandslurs
soundscrape -f chunmeista
soundscrape -f proximity
soundscrape -f dr-oz
soundscrape -f edm
Running all of these getting same problem

**Comment by sergos** [comment]
I worked around it with commenting out /usr/local/lib/python3.5/dist-packages/soundscrape/soundscrape.py line 460:

        except Exception as e:
            puts_safe(colored.red("Problem downloading ") + colored.white(track['title']))
            #puts_safe(e)

**Comment by gamemasta0** [comment]
It might be a more long-term fix to switch out 
`puts_safe(e)`
for
`puts_safe(str(e))`
when trying to print the description of an exception. Switching that code fixed the issue for me since it was having an attribute error looking for a string to print.

**Comment by arnauldb** [comment]
I have the same problem. I tried sergos fix but no luck, then tried gamemasta0 fix but now have this error: 

> Downloading: Pound - Charlie Cuva
> Problem downloading Pound - Charlie Cuva
> 429 Client Error: Unknown for url: https://api.soundcloud.com/tracks/328229282/stream?client_id=175c043157ffae2c6d5fed16c3d95a4c&limit=200

**Comment by bourdeau** [comment]
Hi there,

Just noticed your issue cloned the repo and tried it with Python 3.6 and I got the following error:
```bash
AttributeError: 'HTTPError' object has no attribute 'replace'
```
It seems that "text" in def **puts_safe(text):** is a requests.exceptions.HTTPError and not a string.

It's because in:

```python
        except Exception as e:
            puts_safe(colored.red("Problem downloading ") + colored.white(track['title']))
            puts_safe(e) # <- Should not return requests.exceptions.HTTPError but just message attribute
```
First time I use the lib so maybe I'm wrong.

**Comment by bourdeau** [comment]
HTTP 429 is "Too many requests", I got the same error here. I guess Soundcloud changed it's policy.

**Comment by the-nick-dev** [comment]
Thanks! When the scrapper was throwing an error it was completely stopping the scrapping process! Now it continues to try downloading all next songs!

**Comment by the-nick-dev** [comment]
TODAY NO MORE ERRORS! EVERYTHING WORKS JUST FINE!
