### ISSUE TITLE
Problem "Traceback (most recent call last):"

### ISSUE THREAD

**Issue by spencerthayer** [Miserlou/SoundScrape#210]
I'm having this problem:

```
$ soundscrape spencer4hire -l
Downloading: could be
Problem downloading could be
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/Library/Python/2.7/site-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/Library/Python/2.7/site-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/Library/Python/2.7/site-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/Library/Python/2.7/site-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/Library/Python/2.7/site-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'HTTPError' object has no attribute 'replace'
```

**Comment by Lanchon** [comment]
duplicate of #203, please close

**Comment by spencerthayer** [comment]
Understood.
