### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by thomsan** [Miserlou/SoundScrape#216]
Trying to download https://soundcloud.com/highonmusic1/danrell-x-smaland-hostage
but getting an UnicodeDecodeError on Win10 x64

Traceback (most recent call last):
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 433, in download_tracks
    puts_safe(colored.green("Downloading") + colored.white(": " + track['title']))
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 1313, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 25: invalid continuation                          byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python37-32\Scripts\soundscrape-script.                         py", line 11, in <module>
    load_entry_point('soundscrape==0.30.1', 'console_scripts', 'soundscrape')()
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 459, in download_tracks
    puts_safe(colored.red("Problem downloading ") + colored.white(track['title']))
  File "c:\users\thomas\appdata\local\programs\python\python37-32\lib\site-packages\soundscra                         pe\soundscrape.py", line 1313, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 32: invalid continuation                          byte

**Comment by williamdes** [comment]
That one also breaks the script : https://soundcloud.com/clg-2/pleasant-dream

**Comment by RedBlaze42** [comment]
My fix for this is replace the puts_safe method at the end of the soundscrape.py file by this:
`def puts_safe(text):
    if sys.platform == "win32":
        if sys.version_info < (3,0,0):
            puts(text)
        else:
            try:
                puts(text.encode(sys.stdout.encoding, errors='replace').decode(sys.stdout.encoding,'ignore'))
            except:
                puts("Error")
    else:
        puts(text)`

That's just a workaround not a real fix though

**Comment by SimplicityGuy** [comment]
This should be addressed with PR #214. There is better bad filename detection and filename sanitization.
