### ISSUE TITLE
File name too long UTF-8 long titles

### ISSUE THREAD

**Issue by grea09** [Miserlou/SoundScrape#231]
Ehlo,
I wanted to share an error I encounter frequently with soundscrape. This happens with Japanese songs the most because of UTF-8. I tried a fix in the code but it isn't very straight forward.

Here is a link that would make soundscrape fail : [nice japanese track](https://soundcloud.com/hino-isuka/feat-bootleg-remix)

And here is the logs:

```
Downloading: ゴレマハガト楽団 feat.ふえ吹き野うさぎ - あにまる☆マーチ（ああ…翡翠茶漬け… Bootleg Remix)
Problem downloading ゴレマハガト楽団 feat.ふえ吹き野うさぎ - あにまる☆マーチ（ああ…翡翠茶漬け… Bootleg Remix)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 443, in download_tracks
    filename = download_file(location, track_filename)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 1190, in download_file
    with open(tmp_path, 'wb') as f:
OSError: [Errno 36] File name too long: '翡乃イスカ(Hino Isuka)/翡乃イスカ(Hino Isuka) - ゴレマハガト楽団 feat.ふえ吹き野うさぎ - あにまる☆マーチ（ああ…翡翠茶漬け… Bootleg Remix).mp3.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/usr/local/lib/python3.6/dist-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/home/antoine/.local/lib/python3.6/site-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/home/antoine/.local/lib/python3.6/site-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'OSError' object has no attribute 'replace'
```

The fix I did that worked was to decode the UTF-8 and get the raw char length then try to cut the raw string at the right place as to not have incorrect UTF-8 chars. Then to reencode it. The other issue is when working in an already deep path in the system especially if it has UTF-8 chars in it.

I hope that helps fixing it. I unfortunately don't have the time to recode aand test that fix to do a PR.

Thanks for the awesome tool !!!

**Comment by SimplicityGuy** [comment]
Can you try using the version from PR #214, please? That version fixes how filename sanitization happens, and likely fixes this issue.

**Comment by grea09** [comment]
You mean PR #241 ? I'm trying now with this one with multiple tricky japanese tracks and we'll see.

**Comment by grea09** [comment]
So it seems to work so far, a few unrelated errors I guess. Here is the test playlist along with the output:

```
$ soundscrape -f https://soundcloud.com/grea09/sets/utf8-test
Scraping: サママ・フェスティバル！ (かたぎり Bootleg)
[################################] 8401/8401 - 00:00:00
Scraping: BLACK MIDI - SPEEDWAY (♥ GOJII ♥ RMX)
[################################] 3752/3752 - 00:00:00
Scraping: 梅干茶漬け - Welcome to Kira☆Kira Toyland【WONDER PARADE】
[################################] 2335/2335 - 00:00:00
Scraping: THIS IS STUPID
[################################] 2725/2725 - 00:00:00
Scraping: ファンタジアの空わたって 【 ああああ + Yosk! 】
[################################] 2076/2076 - 00:00:00
Scraping: リトル＊ミュージカル
[################################] 2667/2667 - 00:00:00
Scraping: 通常の20倍の火力を備えたシンデレラ(feat.初音ミク)
[################################] 3481/3481 - 00:00:00
Scraping: ほしとうさぎのシンフォニア 【 あああああみる（ああああ + あみる）】
[################################] 1820/1820 - 00:00:00
Scraping: どんな道だって、続けていこう。
[################################] 3017/3017 - 00:00:00
Scraping: 王子の冒険 をまったり楽しく編曲リレー！
[################################] 2358/2358 - 00:00:00
Scraping: 飯島ゆん＋公式アカウント - Scary Monster Nyanko And Nekomimi - Loli Fu - Zokk
[################################] 6330/6330 - 00:00:00
Scraping: [FREE DL] 青と夏 (かたぎり Bootleg)
[################################] 9715/9715 - 00:00:01
Scraping: かたぎりとゆかいなはなこたち - 花片零式絶対共鳴破壊光線
[################################] 2823/2823 - 00:00:00
Scraping: 〈DEMO〉翡翠茶漬け - TØym/-\t1¢ K!tc#3n!
[################################] 2002/2002 - 00:00:00
Scraping: 〈DEMO〉ああああ＋翡乃イスカ - Keep smiling.
[################################] 2658/2658 - 00:00:00
Scraping: あおぞらのふもと
[################################] 3307/3307 - 00:00:00
CREAM SODA × CRAZY SURFER 【光のチップチューンvs闇のチップチューン対決コンピレーション -Light Side-】 is not downloadable.
Scraping: ボタンひとつで はじまるセカイ▽
[################################] 21191/21191 - 00:00:01
Problem opening file: Is this file a WAV?
Scraping: 【#BM9820AT】P*Light - Poppin' Shower(ISK respect for "P*Style" Remix)【Bootleg】
[################################] 44173/44173 - 00:00:04
Problem opening file: Is this file a WAV?
Scraping: 梅干茶漬け - おわりとはじまりのおと(Owari to Hajimari no Oto) Long Edit
[################################] 3584/3584 - 00:00:00
Scraping: 梅干茶漬け - 別れの涙はまた逢う日まで
[################################] 3316/3316 - 00:00:00
Scraping: VS. マスターコア
[################################] 2460/2460 - 00:00:00
Problem getting track data from: https://api.soundcloud.com/i1/tracks/Shogo Nomura'/streams/?client_id=OmTFHKYSMLFqnu2HHucmclAptedxWXkq&app_version=1481046241
Problem downloading すすめ！うちゅうひこうし
Scraping: 【#BM9820A】P-ChicK-ParK(・◇・) -ﾋﾟｺﾋﾟｺﾋﾟﾖﾋﾟﾖmix!-
[################################] 2685/2685 - 00:00:00
Scraping: ゴレマハガト楽団 feat.ふえ吹き野うさぎ - あにまる☆マーチ（ああ…翡翠茶漬け… Bootleg Remix)
[################################] 2459/2459 - 00:00:00
Scraping: 翡乃イスカ - Gaiaforest(from カラフルマジック☆ワンダーランド！)
[################################] 4320/4320 - 00:00:00
```
I think it is ok to close this issue now.
