### ISSUE TITLE
Can't download Soundcloud likes

### ISSUE THREAD

**Issue by dan-asa** [Miserlou/SoundScrape#253]
I can download individual tracks from soundcloud, but I can't download likes and this error shows up. Any idea why?

`Active code page: 65001
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 183, in process_soundcloud
    resolved2 = soundcloud.resource.ResourceList(resolved2['collection'])
KeyError: 'collection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\soundscrape.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 123, in main
    process_soundcloud(vargs)
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 204, in process_soundcloud
    track_data = get_soundcloud_data(artist_url)
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 489, in get_soundcloud_data
    data['artist'] = title_tag.split(' by ')[1].split('|')[0].strip()
IndexError: list index out of range`

**Comment by markddavidoff** [comment]
Url you input please, just tried with another url and works fine for me. this line depends on soundcloud title saying "X by Y"

**Comment by dan-asa** [comment]
I tried using **_soundscrape  fdd-dan -l_** and **_soundscrape  https://soundcloud.com/fdd-dan -l_**

Basically I tried to get the liked tracks from my account. I tried now with a different account and it works.
Maybe it's the "-" character from the name?

**Comment by markddavidoff** [comment]
potential fix: @Miserlou https://github.com/Miserlou/SoundScrape/pull/254

**Comment by dan-asa** [comment]
I replaced soundscrape.py with the one from the fix and unfortunately I got a similar error.

`soundscrape  fdd-dan -l -f
Active code page: 65001
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 179, in process_soundcloud
    if('next_href' in resolved2):
TypeError: argument of type 'Resource' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\soundscrape.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 123, in main
    process_soundcloud(vargs)
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 203, in process_soundcloud
    track_data = get_soundcloud_data(artist_url)
  File "c:\program files\python39\lib\site-packages\soundscrape\soundscrape.py", line 488, in get_soundcloud_data
    data['artist'] = title_tag.split(' by ')[1].split('|')[0].strip()
IndexError: list index out of range`

**Comment by markddavidoff** [comment]
Ah yes, lol, i forgot about the code above it as ive been using soundcloud
as an import and not as a module via the cli. Ill update my pr.

**Comment by markddavidoff** [comment]
I believe its the number of likes that is the key factor and it is the
pagination that does not work

**Comment by markddavidoff** [comment]
I've updated my pr, should work now @FDDdan #254

**Comment by dan-asa** [comment]
Thanks a lot, it works!
