### ISSUE TITLE
ImportError: cannot import name 'wrapped_resource' from 'soundcloud.resource'

### ISSUE THREAD

**Issue by 7k50** [Miserlou/SoundScrape#265]
I have just installed SoundScrape for Python 3.9.9.

To test it, I tried downloading something from Bandcamp:

`soundscrape warsaw -b -f`

Gives the error:

```
Traceback (most recent call last):
  File "/my/path/py390/bin/soundscrape", line 5, in <module>
    from soundscrape.soundscrape import main
  File "/my/path/py390/lib/python3.9/site-packages/soundscrape/soundscrape.py", line 8, in <module>
    import soundcloud
  File "/my/path/py390/lib/python3.9/site-packages/soundcloud/__init__.py", line 8, in <module>
    from soundcloud.client import Client
  File "/my/path/py390/lib/python3.9/site-packages/soundcloud/client.py", line 7, in <module>
    from soundcloud.resource import wrapped_resource
ImportError: cannot import name 'wrapped_resource' from 'soundcloud.resource' (/my/path/py390/lib/python3.9/site-packages/soundcloud/resource/__init__.py)
```

**Comment by 89z** [comment]
Please provide link to what you are trying to download

**Comment by 7k50** [comment]
> Please provide link to what you are trying to download

I am using the example in the Readme: https://github.com/Miserlou/SoundScrape#bandcamp

`soundscrape warsaw -b -f`

But just taking any random release from Bandcamp seems to create the same error:

`soundscrape https://djoko.bandcamp.com/album/get-sexy-ep -b -f`

_"ImportError: cannot import name 'wrapped_resource' from 'soundcloud.resource"_

Assuming I am using the right syntax?

**Comment by 89z** [comment]
If youre interested, I have an alternate tool available:

~~~
PS C:\> bandcamp -i https://djoko.bandcamp.com/album/get-sexy-ep
HEAD https://djoko.bandcamp.com/album/get-sexy-ep
GET http://bandcamp.com/api/mobile/24/tralbum_details?band_id=1&tralbum_id=3363779785&tralbum_type=a
{Track_Num:1 Title:Terminate the Machine Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=1351384569&ts=1639236095&t=8fc9377b0cc69df9fd647d138ebf87db4da0751f}}
{Track_Num:2 Title:Namaste Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=308325049&ts=1639236095&t=5a15f5da7e0047628bc55f7ac7708eec120ad93d}}
{Track_Num:3 Title:Totally Lost Focus Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2255489380&ts=1639236095&t=1905666a39ff8e3215a893288df2b2ab708b9ea1}}
{Track_Num:4 Title:Get Sexy Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=446649198&ts=1639236095&t=6b9bc2d68cb8cb74469b5f6333b91a95b5101073}}
~~~

https://github.com/89z/mech

**Comment by 7k50** [comment]
Something must have been wrong with my install. Tried reinstalling some packages and it works as intended.
