### ISSUE TITLE
 error in demjson setup command: use_2to3 is invalid

### ISSUE THREAD

**Issue by ryanbuckleyca** [Miserlou/SoundScrape#272]
i tried `pip install soundscrape demjson==2.2.3` too but it didn't work.

```
➜  ~ pip install soundscrape
Collecting soundscrape
  Downloading soundscrape-0.31.0-py3-none-any.whl (16 kB)
Collecting args>=0.1.0 (from soundscrape)
  Downloading args-0.1.0.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting clint>=0.3.2 (from soundscrape)
  Downloading clint-0.5.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting demjson>=2.2.2 (from soundscrape)
  Downloading demjson-2.2.4.tar.gz (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.5/131.5 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in demjson setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by soulwax** [comment]
My original comment was:

Using miniconda3, after installation:

1. `conda init`
2. `conda create --name <name_your_env> python=3.9`
3. `conda activate <name_your_env>`
4. `pip install "setuptools<58.0.0"`
5. `pip install soundscrape`
Edit, turns out step 6 was also required for me:
6. `pip install six`

Then:
`soundscrape --help` should work.

`soundscrape --help` works fine then, but even if I use their own examples:
`soundscrape rabbit-i-am -n 3` - there's errors.

The issue I encounter now was shared [here](https://github.com/Miserlou/SoundScrape/issues/272#issuecomment-1962749626).
I believe currenctly the issues run deeper than just versions or dependencies. Pure conjecture: Scraping music off of soundcloud has become more obfuscated and this repo/package did not "go with the times".

A `selenium` approach may be of necessity now.

**Comment by ryanbuckleyca** [comment]
I eventually got it to work with installing python 3.9, installing "setuptools<58.0.0" and then running `pip install soundscrape demjson==2.2.3` again.

now i'm noticing the Client ID is likely out of date:
```
Traceback (most recent call last):
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundscrape/soundscrape.py", line 188, in process_soundcloud
    resolved = client.get('/resolve', url=artist_url, limit=200)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Fperlair%2Fbaby1&limit=200&client_id=a3dd183a357fcff9a6943c0d65664087

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ry/Library/Python/3.11/bin/soundscrape", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundscrape/soundscrape.py", line 123, in main
    process_soundcloud(vargs)
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundscrape/soundscrape.py", line 222, in process_soundcloud
    filename = download_file(hard_track_url, filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ry/Library/Python/3.11/lib/python/site-packages/soundscrape/soundscrape.py", line 1224, in download_file
    if url[0:2] == '//':
       ~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
```

seems related to: https://github.com/Miserlou/SoundScrape/issues/261

**Comment by soulwax** [comment]
I confirm what [the guy above me](https://github.com/Miserlou/SoundScrape/issues/272#issuecomment-1962749626) said.

Did you also have to do step 6 - `pip install six` as it was for me?

**Comment by Twten** [comment]
keep getting this once i install python 3.9 and installing setuptools<58.0.0". i don't even know what to try anymore.
`Defaulting to user installation because normal site-packages is not writeable
Collecting soundscrape
  Using cached soundscrape-0.31.0-py3-none-any.whl.metadata (6.3 kB)
Collecting demjson==2.2.3
  Using cached demjson-2.2.3.tar.gz (131 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by Twten** [comment]
keep getting this once i install python 3.9 and installing setuptools<58.0.0". i don't even know what to try anymore.

`Defaulting to user installation because normal site-packages is not writeable
Collecting soundscrape
  Using cached soundscrape-0.31.0-py3-none-any.whl.metadata (6.3 kB)
Collecting demjson==2.2.3
  Using cached demjson-2.2.3.tar.gz (131 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by Twten** [comment]
keep getting this once i install python 3.9 and installing setuptools<58.0.0". i don't even know what to try anymore.

```Defaulting to user installation because normal site-packages is not writeable
Collecting soundscrape
Using cached soundscrape-0.31.0-py3-none-any.whl.metadata (6.3 kB)
Collecting demjson==2.2.3
Using cached demjson-2.2.3.tar.gz (131 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
ERROR: Can not execute setup.py since setuptools is not available in the build environment.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Sakkenn** [comment]
same

**Comment by FoobarProtocol** [comment]
Came to this issue after running into the same problem. Code is unmaintained and like another commenter mentioned...Soundcloud has updated its site in various ways since the release of this repo. 

Good news though is that (in my experience)  its been relatively easy to download tracks from soundcloud (using a plethora of tools). I explored this tool due to my desire to download all of my 'liked' tracks from my profile since there are a ton of them and this would represent the ultimate playlist (imo). 

Since most playlist info is open to the public (unless there's a setting for someone to hide their 'likes'), there shouldn't be anything peculiar on Soundcloud's site that would stop: 

1. A modified tool from scraping the URLs for each individual file in a given set / "likes" for a specific user. 

2. Batching requests for downloads (rate limiting / pauses etc.), to avoid detection; maybe even some old fashioned user-agent spoofing could be useful. 

3. Perhaps a tool to grab the cookie / token from a soundcloud login directly from the Terminal. Either by having someone enter the login credentials or searching common paths for commonly used Browsers (users can select which one; Chrome, Firefox, Brave, Safari etc.), then setting it as an environment variable (i.e., `SOUNDCLOUD_TOKEN`). 

I'm just writing this comment for those that may read this in the future.

**Comment by soulwax** [comment]
At this point I can only recommend https://github.com/scdl-org/scdl instead or plain yt-dlp with ffmpeg
