### ISSUE TITLE
"Trackback ..." message -- no  downloads?

### ISSUE THREAD

**Issue by chimmel** [Miserlou/SoundScrape#33]
I installed soundscrape, but trying to use it this is the response I get:

➜  ~  sudo pip install soundscrape
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting soundscrape
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading soundscrape-0.16.1.tar.gz
Collecting args>=0.1.0 (from soundscrape)
  Downloading args-0.1.0.tar.gz
Collecting clint>=0.3.2 (from soundscrape)
  Downloading clint-0.5.1.tar.gz
Collecting demjson==2.2.2 (from soundscrape)
  Downloading demjson-2.2.2.tar.gz (130kB)
    100% |████████████████████████████████| 131kB 629kB/s 
Collecting fudge==1.0.3 (from soundscrape)
  Downloading fudge-1.0.3.tar.gz (87kB)
    100% |████████████████████████████████| 90kB 992kB/s 
Collecting mutagen==1.22 (from soundscrape)
  Downloading mutagen-1.22.tar.gz (813kB)
    100% |████████████████████████████████| 815kB 406kB/s 
Collecting requests>=2.1.0 (from soundscrape)
  Downloading requests-2.8.0-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 479kB 490kB/s 
Collecting simplejson==3.3.1 (from soundscrape)
  Downloading simplejson-3.3.1.tar.gz (67kB)
    100% |████████████████████████████████| 69kB 1.1MB/s 
Collecting soundcloud>=0.4.1 (from soundscrape)
  Downloading soundcloud-0.4.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from soundscrape)
Installing collected packages: args, clint, demjson, fudge, mutagen, requests, simplejson, soundcloud, soundscrape
  Running setup.py install for args
  Running setup.py install for clint
  Running setup.py install for demjson
  Running setup.py install for fudge
  Running setup.py install for mutagen
  Running setup.py install for simplejson
  Running setup.py install for soundcloud
  Running setup.py install for soundscrape
Successfully installed args-0.1.0 clint-0.5.1 demjson-2.2.2 fudge-1.0.3 mutagen-1.22 requests-2.8.0 simplejson-3.3.1 soundcloud-0.4.1 soundscrape-0.16.1
➜  ~  soundscrape https://soundcloud.com/mrsuicidesheep/sven-van-hees-soda-pressing
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.1.0
➜  ~  soundscrape
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.1.0
➜  ~  sudo soundscrape https://soundcloud.com/mrsuicidesheep/sven-van-hees-soda-pressing
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.1.0
➜  ~  
Last login: Thu Oct  8 09:32:35 on ttys000
➜  ~  soundscrape
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.1.0
➜  ~  soundscrape https://soundcloud.com/mrsuicidesheep/sven-van-hees-soda-pressing
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.1.0
➜  ~  

Where are the files supposed to be saved to? What do the above messages mean? Thanks.

**Comment by Miserlou** [comment]
Your pip is messed up. You don't need 'sudo' to install SC.

The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
