### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ceeveeya** [Miserlou/SoundScrape#35]
Works fine! Thank u for this one.
But I got an error. In my case mix has an apostrophe in title. And I suppose that's the reason it falls to error.
```bash
[cv@emy sets]$ soundscrape https://www.mixcloud.com/paulvandyk/paul-van-dyks-vonyc-sessions-477-allen-envy/
Traceback (most recent call last):
  File "/usr/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.18.1', 'console_scripts', 'soundscrape')()
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 63, in main
    process_mixcloud(vargs)
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 333, in process_mixcloud
    filenames = scrape_mixcloud_url(mc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'])
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 367, in scrape_mixcloud_url
    puts(colored.green(u"Downloading") + ': ' + data['artist'].encode('utf-8') + " - " + data['title'].encode('utf-8') + " (" + track_filename[-4:] + ")")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
```

**Comment by Miserlou** [comment]
Fixed - thanks for reporting!
