### ISSUE TITLE
pkg_resources.UnknownExtra: requests 2.3.0 has no such extra feature 'security'

### ISSUE THREAD

**Issue by Deleetdk** [Miserlou/SoundScrape#40]
I installed it using pip. I am running Windows 8.1 64-bit using python 2.7.7 (via Anaconda). Traceback below:

Z:\Musik\MOON>soundscrape.exe moon_music
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\soundscrape-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg\pkg_resources.py"
, line 2829, in <module>
  File "C:\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg\pkg_resources.py"
, line 449, in _build_master
  File "C:\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg\pkg_resources.py"
, line 742, in require
  File "C:\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg\pkg_resources.py"
, line 644, in resolve
  File "C:\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg\pkg_resources.py"
, line 2367, in requires
pkg_resources.UnknownExtra: requests 2.3.0 has no such extra feature 'security'

Ideas?

**Comment by Miserlou** [comment]
Hm. Never tried on windows. Not sure.. 

¯\_(ツ)_/¯

Want to try to investigate it?

**Comment by wzzle** [comment]
I'm on Ubuntu 14.04 and got the same issue:

Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'

**Comment by wzzle** [comment]
After installing libpython2.7-dev and uninstalling/reinstalling everything I got some new errors with missing pip packages. After installing the missing packages it finally works now.

**Comment by Miserlou** [comment]
On a fresh 14.04 install, pip install soundscrape works just fine. Have not tried with p3 or w32.

**Comment by lowend** [comment]
which pip packages are missing? I am receiving the same error and hoping to fix.

  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'

Linux Mint 17.1

**Comment by Miserlou** [comment]
Should be fixed with version bump, please re-open if not.
