### ISSUE TITLE
pkg_resources.DistributionNotFound: wheel==0.24.0

### ISSUE THREAD

**Issue by bsans** [Miserlou/SoundScrape#44]
Similar to @dslackw in #9, I'm having issues with a pip installation of a dependency.

I've tried using the `--no-cache-dir` option and a few other tips in [this SO post](http://stackoverflow.com/questions/9510474/removing-pips-cache), to no avail.

Something seems whacky with the way pip is associating the dependencies.

Full traceback:

```
[soundscrape_test]$ soundscrape stolensnares
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: wheel==0.24.0
```

**Comment by Miserlou** [comment]
Wheel is now >=0.24.0
