### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u266b' in position 55: ordinal not in range(128)

### ISSUE THREAD

**Issue by Wojtas121PL** [Miserlou/SoundScrape#46]
It happend to me while i was trying to download this set:
https://soundcloud.com/angrysausage/sets/undertale-toby-fox

First 5 songs went through without any problems but then on the 6th song it crashed.
Its probably due to the 6th song's name having ♫ sing at the end of title:
Toby Fox - UNDERTALE Soundtrack - 06 Uwa!! So Temperate♫

Here is the whole error:

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 74, in main
    process_soundcloud(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 133, in process_soundcloud
    filenames = download_tracks(client, tracks, num_tracks, vargs['downloadable'], vargs['folders'], id3_extras=id3_extras)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 226, in download_tracks
    puts(colored.red("Problem downloading ") + track['title'])
  File "c:\python27\lib\site-packages\clint\textui\colored.py", line 105, in __add__
    return str(self.color_str) + str(other)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u266b' in position 55: ordinal not in range(128)

I was trying to fix it myself but im horibble at python :/

Please help and thank you in advance :-)

**Comment by lowend** [comment]
seems to be a similar issue on @flyingrub's scdl, it's the special characters in the name!

https://github.com/flyingrub/scdl/issues/94

I have also had the same error using Soundscrape :)

soundscrape https://soundcloud.com/rufussounds/sets/r-f-s-and-friends-triple-j-mix
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.23.3', 'console_scripts', 'soundscrape')()
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 74, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 133, in process_soundcloud
    filenames = download_tracks(client, tracks, num_tracks, vargs['downloadable'], vargs['folders'], id3_extras=id3_extras)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 226, in download_tracks
    puts(colored.red("Problem downloading ") + track['title'])
  File "/usr/local/lib/python2.7/dist-packages/clint/textui/colored.py", line 105, in __add__
    return str(self.color_str) + str(other)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 1: ordinal not in range(128)

**Comment by arob49012** [comment]
I can't replicate either error with a fresh install of soundscrape using pip

**Comment by antipathia** [comment]
I can't replicate either error with a fresh install of soundscrape using pip, everything downloads as it should!
