### ISSUE TITLE
ImportError: No module named mutagen.mp3

### ISSUE THREAD

**Issue by ben-page** [Miserlou/SoundScrape#52]
I installed soundscrape using pip on Windows 10 x64. The mutagen dependency does not seem to be property installed: 

```
$ soundscrape.exe https://soundcloud.com/xxxx
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 13, in <module>
    from mutagen.mp3 import MP3, EasyMP3
ImportError: No module named mutagen.mp3
```

I manually downloaded, built, and installed mutagen. Now soundscrape works perfectly.

**Comment by ben-page** [comment]
Scratch that, not perfectly. No errors were thrown, but the ID3 tag info was not set.

**Comment by TetraEtc** [comment]
As of latest update this should be fixed

**Comment by SimplicityGuy** [comment]
Unrelated to SoundScrape; this is about the installation of mutagen on Windows.
