### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by OpenKerley** [Miserlou/SoundScrape#58]
Whenever I try to download a song containing a character from a foreign langauge, the program throws the following error.

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

**Comment by DevinWatson** [comment]
I am also having issues with unicode characters:
```
DownloadingProblem downloading Traceback (most recent call last):
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\soundscrape\soundscrape.py", line 212, in download_tracks
  puts(colored.green("Downloading") + colored.white(": " + track['title']))
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\textui\core.py", line 68, in puts
  stream(_str)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 34, in write
  self.__convertor.write(text)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 115, in write
  self.write_and_convert(text)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 139, in write_and_convert
  self.write_plain_text(text, cursor, start)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 147, in write_plain_text
  self.wrapped.write(text[start:end])
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\encodings\cp437.py", line 19, in encode
  return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2020' in position 18: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
  "__main__", mod_spec)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
  exec(code, run_globals)
File "C:\Users\Devin\AppData\Local\Programs\Python\Python35-32\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\soundscrape\soundscrape.py", line 74, in main
  process_soundcloud(vargs)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\soundscrape\soundscrape.py", line 138, in process_soundcloud
  filenames = download_tracks(client, tracks, num_tracks, vargs['downloadable'], vargs['folders'], id3_extras=id3_extras)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\soundscrape\soundscrape.py", line 232, in download_tracks
  puts(colored.red("Problem downloading ") + colored.white(track['title']))
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\textui\core.py", line 68, in puts
  stream(_str)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 34, in write
  self.__convertor.write(text)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 115, in write
  self.write_and_convert(text)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 139, in write_and_convert
  self.write_plain_text(text, cursor, start)
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 147, in write_plain_text
  self.wrapped.write(text[start:end])
File "c:\users\devin\appdata\local\programs\python\python35-32\lib\encodings\cp437.py", line 19, in encode
  return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2020' in position 16: character maps to <undefined>

```

**Comment by DevinWatson** [comment]
@OpenKerley This seems to be an issue with the Windows console. There are several code workarounds but none of them seem to be ideal. I was able to get around this issue with [this](http://stackoverflow.com/a/32176732).

C:\> py -mpip install win-unicode-console
C:\> py -mrun soundscrape.py <xxxxxxx>

**Comment by OpenKerley** [comment]
@DevinWatson I ended up using the following
`if _platform == "win32":
        os.system("chcp 65001");`

**Comment by Miserlou** [comment]
Added OpeKerley's hack
