### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#62]
$ sof https://soundcloud.com/ministryofsoundaus/dirtcaps-x-tom-piper-rudeboi-1
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 74, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 105, in process_soundcloud
    resolved = client.get('/resolve', url=artist_url, limit=200)
  File "/usr/local/lib/python2.7/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python2.7/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/221944626?client_id=22e566527758690e6feb2b5cb300cc43

**Comment by justinglavin** [comment]
Also observing this error

$ soundscrape https://soundcloud.com/zhu/in-the-morning
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.23.5', 'console_scripts', 'soundscrape')()
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 74, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 105, in process_soundcloud
    resolved = client.get('/resolve', url=artist_url, limit=200)
  File "/usr/local/lib/python2.7/dist-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python2.7/dist-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/248853453?client_id=22e566527758690e6feb2b5cb300cc43

**Comment by Miserlou** [comment]
Not sure about this one, thanks for confirming.

**Comment by Miserlou** [comment]
Very very very crude fix in master, more soon.

**Comment by alexgorbatchev** [comment]
same issue ```soundscrape https://soundcloud.com/the-bob-moses/bob-moses-essential-mix-2016```

**Comment by alexgorbatchev** [comment]
@Miserlou I'm not a Python person. How could I install from master? (or maybe you could push the fix out?)

**Comment by Miserlou** [comment]
Works fine now.
