### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by iraritchiemeek** [Miserlou/SoundScrape#63]
soundscrape https://urbnet.bandcamp.com/album/spirit-of-the-golden-era
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.22.1', 'console_scripts', 'soundscrape')()
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 67, in main
    process_bandcamp(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 246, in process_bandcamp
    filenames = scrape_bandcamp_url(bc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'])
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 272, in scrape_bandcamp_url
    album_data = get_bandcamp_metadata(url)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 377, in get_bandcamp_metadata
    output['genre'] = ' '.join(str(s) for s in tags)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 377, in <genexpr>
    output['genre'] = ' '.join(str(s) for s in tags)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u202c' in position 20: ordinal not in range(128)

**Comment by Miserlou** [comment]
Works fine now. These are cool beats.
