### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by bakera81** [Miserlou/SoundScrape#68]
I love soundscrape and have been using it for a while. I recently upgraded pip, and now I get this error:

  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Soundscrape still works great for some songs, so I suspect that there may be more to the issue than meets the eye.

**Comment by Miserlou** [comment]
Thanks, which track was this on? I need to know to reproduce.

Soundcloud is changing up a bunch of stuff lately and things are breaking all over.. Turbulent times ahead..

**Comment by bakera81** [comment]
Sure, there were several:
https://soundcloud.com/kaskade/kaskade-live-at-ultra-music-festival-miami-march-18-2016 
https://soundcloud.com/kaskade/kaskade-tear-down-these-walls-ft-tamra-keenan
https://soundcloud.com/majorlazer/major-lazer-wave-feat-kali-uchis
https://soundcloud.com/actionbronson/bronson-x-jah-tiger-x-meyhem-mr-2-face-off-blue-chips-7000

I don't know if it's useful, but two songs that did work were:
 https://soundcloud.com/dvsndvsn/too-deep
https://soundcloud.com/kiiaraonline/gold

**Comment by Miserlou** [comment]
This should all be fixed now! Thanks for reporting.

**Comment by ChipWolf** [comment]
Still not solved. https://soundcloud.com/muse 
```
(soundscrape) ➜  soundscrape soundscrape muse
Traceback (most recent call last):
  File "/Users/Chip/Documents/Utilities/soundscrape/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 270, in process_soundcloud
    data = get_soundcloud_api2_data(artist_id)
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 494, in get_soundcloud_api2_data
    parsed = response.json()
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/Users/Chip/Documents/Utilities/soundscrape/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
