### ISSUE TITLE
Download Issue : 05/27/2016

### ISSUE THREAD

**Issue by tsmekiran** [Miserlou/SoundScrape#80]
Hi,
Do you know what issue this is.
I am not able to download anymore.

soundscrape https://soundcloud.com/foolsgoldrecs/danny-brown-dip

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 74, in main
    process_soundcloud(vargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 110, in process_soundcloud
    resolved = client.get('/resolve', url=artist_url, limit=200)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Ffoolsgoldrecs%2Fdanny-brown-dip&limit=200&client_id=22e566527758690e6feb2b5cb300cc43

**Comment by Miserlou** [comment]
You'll need to use the updated client.

pip install soundscrape --upgrade

**Comment by Miserlou** [comment]
DIP YOU DIP I DIP

SUHHHHH

**Comment by tsmekiran** [comment]
Thanks miserlou.
Ill upgrade and check this.
