### ISSUE TITLE
No attribute 'message'

### ISSUE THREAD

**Issue by yrcnv** [Miserlou/SoundScrape#81]
If using python3: for some tracks (for example [this](https://soundcloud.com/giuseppeottaviani/192k-giuseppe-ottaviani-go-on-air-196) and [this](https://soundcloud.com/edxmusic/edx-no-xcuses-272-presented-by-thenocturnaltimescom)) there is an AttributeError.

If using python2 it can download but doesn't rename the file and doesn't write ID tags.

```python
soundscrape https://soundcloud.com/giuseppeottaviani/192k-giuseppe-ottaviani-go-on-air-196
Traceback (most recent call last):
  File "/home/cv/.local/lib/python3.5/site-packages/soundscrape/soundscrape.py", line 115, in process_soundcloud
    resolved = client.get('/resolve', url=artist_url, limit=200)
  File "/usr/lib/python3.5/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python3.5/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/266153828?client_id=175c043157ffae2c6d5fed16c3d95a4c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/home/cv/.local/lib/python3.5/site-packages/soundscrape/soundscrape.py", line 77, in main
    process_soundcloud(vargs)
  File "/home/cv/.local/lib/python3.5/site-packages/soundscrape/soundscrape.py", line 121, in process_soundcloud
    item_id = e.message.rsplit('/', 1)[-1].split('.json')[0].split('?client_id')[0]
AttributeError: 'HTTPError' object has no attribute 'message'
```

**Comment by Miserlou** [comment]
Fixed, I think.
