### ISSUE TITLE
KeyError: u'track'

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#90]
~/Music $ sof https://soundcloud.com/puptheband
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 83, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 182, in process_soundcloud
    track = track['track']
KeyError: u'track'

**Comment by Miserlou** [comment]
Fixed in 0.25.0
