### ISSUE TITLE
Support for HTTP urls on custom domains

### ISSUE THREAD

**Issue by RAnders00** [Miserlou/SoundScrape#93]
This is an issue that occurs when using custom domain bandcamp sites. HTTPS is not available for them and the script errors because it assumes HTTPS is ok.

Related:

 * #91
 * https://github.com/Miserlou/SoundScrape/commit/b0b863ae8d6a93049a4f7959ac359a6a313b92a2

Error message when running with `soundscrape -b http://music.monstercat.com/`:

    Traceback (most recent call last):
      File "c:\tools\python2\lib\runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "c:\tools\python2\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\tools\python2\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
      File "c:\tools\python2\lib\site-packages\soundscrape\soundscrape.py", line 75, in main
        process_bandcamp(vargs)
      File "c:\tools\python2\lib\site-packages\soundscrape\soundscrape.py", line 410, in process_bandcamp
        filenames = scrape_bandcamp_url(bc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'])
      File "c:\tools\python2\lib\site-packages\soundscrape\soundscrape.py", line 439, in scrape_bandcamp_url
        album_data = get_bandcamp_metadata(url)
      File "c:\tools\python2\lib\site-packages\soundscrape\soundscrape.py", line 519, in get_bandcamp_metadata
        request = requests.get(url)
      File "c:\tools\python2\lib\site-packages\requests\api.py", line 71, in get
        return request('get', url, params=params, **kwargs)
      File "c:\tools\python2\lib\site-packages\requests\api.py", line 57, in request
        return session.request(method=method, url=url, **kwargs)
      File "c:\tools\python2\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "c:\tools\python2\lib\site-packages\requests\sessions.py", line 585, in send
        r = adapter.send(request, **kwargs)
      File "c:\tools\python2\lib\site-packages\requests\adapters.py", line 467, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='http', port=443): Max retries exceeded with url: //music.monstercat.com/.bandcamp.com/music (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004294748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by Miserlou** [comment]
Right you are!

**Comment by Miserlou** [comment]
I think this may actually just have been a packing error because it works in master but not deployed 0.21.1

**Comment by Miserlou** [comment]
Packaging error confirmed, 0.25.2 published.

**Comment by RAnders00** [comment]
Thanks for clearing it up! 👍 This is such a great project.
